language: php

php:
  - 7.1

notifications:
  email:
    - stumpdenmark@hotmail.com

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

#stop travis mysql
before_install:
  - sudo service mysql stop
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

# setup infrastructure using docker-compose
install:
  - docker-compose -f docker-compose-webserver.deploy.yml up -d --force-recreate solr nginx composer db phalcon
  - sleep 120

# run tests inside Phalcon container
script:
  - docker-compose -f docker-compose-webserver.deploy.yml exec phalcon /code/vendor/bin/phpunit

after_success:
  # remove dev dependencies
  - docker-compose -f docker-compose-webserver.deploy.yml run --entrypoint "rm -rf /code/vendor" composer
  # Install production dependencies
  - docker-compose -f docker-compose-webserver.deploy.yml run composer install --prefer-dist --no-dev --optimize-autoloader
  # build and run deployment container
  - #docker-compose -f docker-compose-webserver.deploy.yml build deploy
  - #docker-compose -f docker-compose-webserver.deploy.yml run deploy
  # new test
  - set -e
  - sudo apt-get install -y lftp

  - lftp -c -c "set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate false; open sftp://$FTP_USER:$KBHKILDER_FTP_PASS@$KBHKILDER_FTP_HOST:22; "mirror -R --delete --exclude-glob **/.env --exclude-glob  /vendor/**/test**/*.php --exclude-glob *.yml --exclude-glob tests_api/** --no-empty-dirs --depth-first  --use-pget-n=15 --verbose=3 ${KBHKILDER_FTP_PATH} .; quit;"


before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'