version: '2'
services:
  indexer:
    container_name: indexer
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/apacs-indexer:{image-tag}
    networks:
      - default
  solr:
    container_name: solr
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/apacs-solr:{image-tag}
    ports:
      - "80:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
      - -Ddisable.configEdit=true
    volumes:
      - banana_core:/opt/solr/server/solr/banana-int/
      - mycores:/opt/solr/server/solr/mycores
    networks:
      - default
volumes:
    banana_core:
    mycores:
networks:
  default:
