version: '3.6'
services:
  phalcon:
    build:
      context: ./
      dockerfile: ./infrastructure/php-fpm-phalcon/Dockerfile_prod
    container_name: phalcon
    depends_on:
      - composer
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
       - "80:80"
  composer:
      container_name: composer
      restart: 'no'
      image: composer/composer:php7
      command: update --no-dev
      working_dir: /code
      volumes:
        - ./apacs:/code
  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456   
      MYSQL_USER: ${MYSQL_USER}   
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}   
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  solr:
    container_name: solr
    build:
      context: infrastructure/solr/
      dockerfile: infrastructure/solr/Dockerfile
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core      
networks:
    default:
