version: '2'
services:
  phalcon:
    build:
      context: ./
      dockerfile: ./docker_webserver/Dockerfile
    container_name: webserver
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./apacs:/var/www/
    environment:
      - PROD_DEV=DEV
  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./apacs/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs
  solr:
    image: library/solr:6.6
    container_name: solr
    ports:
      - "8989:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
        - ./solr_conf:/opt/solr/server/solr/configsets/solr_conf
