version: '2'
services:
  indexer:
    container_name: indexer
    build:
        context: ./
        dockerfile: ./infrastructure/indexing/Dockerfile_prod
    networks:
      - default
  solr:
    container_name: solr
    build:
      context: ./infrastructure/solr/
    ports:
      - "80:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
      - -Ddisable.configEdit=true
    volumes:
      - banana_core:/opt/solr/server/solr/banana-int/
      - mycores:/opt/solr/server/solr/mycores
    networks:
      - default
volumes:
    banana_core:
    mycores:
networks:
  default:
