version: '3.3'
services:

  apacs:
    build:
      context: ./
      dockerfile: ./infrastructure/php-fpm-phalcon/Dockerfile_dev
    container_name: apacs
    depends_on:
      - composer
      - mysql
      - solr
    volumes:
      - ./apacs:/code
      - ./infrastructure/php-fpm-phalcon/php-override.ini.dev:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - composer-vendor:/code/vendor
    env_file:
      - .env_dev
  
  composer:
    container_name: composer
    build:
      context: ./infrastructure/composer/
      dockerfile: Dockerfile
    command: install --ignore-platform-reqs
    restart: 'no'
    volumes:
      - ./apacs:/app
      - composer-vendor:/app/vendor

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./apacs/tests/TestHelpers/db-test-data:/docker-entrypoint-initdb.d
      - ./infrastructure/db/config/my_dev.cnf:/etc/mysql/conf.d/my_dev.cnf:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs

  nginx:
      image: nginx:alpine
      container_name: nginx
      depends_on:
        - apacs
      volumes:
        - ./infrastructure/nginx/nginx_site.conf:/etc/nginx/conf.d/default.conf
        - ./apacs/tests/test-assets:/code/public/api/test-assets
      ports:
       - "8080:80"

  solr:
    image: library/solr:8.7
    container_name: solr
    ports:
      - "8989:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
        - ./infrastructure/solr/solr_conf:/opt/solr/server/solr/configsets/solr_conf
        - ./infrastructure/solr/web.xml:/opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml
volumes:
  composer-vendor:

networks:
  default:
