version: '2'
services:
  phalcon:
    build: ./docker_webserver/
    container_name: webserver
    privileged: true
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./apacs:/var/www/
    environment:
      - PROD_DEV=DEV
  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./apacs/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs
