version: '2'
services:
  indexer:
    container_name: indexer
    build:
        context: ./
        dockerfile: ./infrastructure/indexing/Dockerfile
    links:
      - "solr"
  solr:
    container_name: solr
    build:
      context: ./infrastructure/solr/
    ports:
      - "80:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
