version: '2'
services:
  indexer:
    container_name: indexer
    build:
        context: ./
        dockerfile: ./infrastructure/indexing/Dockerfile_prod
    networks:
      - default
  solr:
    container_name: solr
    build:
      context: ./infrastructure/solr/
    ports:
      - "80:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
      - stats_core:/opt/solr/server/solr/banana-int/
      ##- apacs_core:/opt/solr/server/solr/mycores/apacs_core/
    networks:
      - default
volumes:
    stats_core:
    apacs_core:
networks:
  default:
