version: '3.3'
services:
  # APACS source code
  apacs:
    build:
      context: ./
      dockerfile: ./infrastructure/php-fpm-phalcon/Dockerfile_prod
    image: apacs:latest
    container_name: apacs
    environment:
      - APACS_ACCESS_CTRL_NAME=${APACS_ACCESS_CTRL_NAME}

      - APACS_DB_CHARSET=${APACS_DB_CHARSET}
      - APACS_DB_DATABASE=${APACS_DB_DATABASE}
      - APACS_DB_HOST=${APACS_DB_HOST}
      - APACS_DB_PASSWORD=${APACS_DB_PASSWORD}
      - APACS_DB_PORT=${APACS_DB_PORT}
      - APACS_DB_USER=${APACS_DB_USER}

      - APACS_IMAGE_PATH=${APACS_IMAGE_PATH}
      - APACS_IMAGE_PROTOCOL=${APACS_IMAGE_PROTOCOL}

      - ENVIRONMENT=${ENVIRONMENT}

      - SOLR_HOST=${SOLR_HOST}
      - SOLR_INTERNAL_URL=${SOLR_INTERNAL_URL}
      - SOLR_PASSWORD=${SOLR_PASSWORD}
      - SOLR_PATH=${SOLR_PATH}
      - SOLR_PORT=${SOLR_PORT}
      - SOLR_SCHEME=${SOLR_SCHEME}
      - SOLR_TIMEOUT=${SOLR_TIMEOUT}
      - SOLR_USERNAME=${SOLR_USERNAME}

      - AUTH0_JWKS_URI=${AUTH0_JWKS_URI}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_MANAGEMENT_AUDIENCE=${AUTH0_MANAGEMENT_AUDIENCE}
      - AUTH0_CACHE_LOCATION=${AUTH0_CACHE_LOCATION}
      - AUTH0_CACHE_DURATION=${AUTH0_CACHE_DURATION}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}

  # Nginx routes requests to APACS
  nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
        - ./infrastructure/nginx/nginx_site.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - apacs
      ports:
       - "80:80"

networks:
    default:
