version: '2'
services:
  phalcon2:
    build:
      context: ./infrastructure/php-fpm-phalcon
      dockerfile: ./infrastructure/php-fpm-phalcon/Dockerfile_dev
    container_name: phalcon2
    depends_on:
      - composer
    volumes:
      - ./apacs:/code
    environment:
      - PHP_ENV=DEV
  nginx2:
      image: nginx:alpine
      container_name: nginx2
      volumes:
        - ./apacs:/code
        - ./infrastructure/php-fpm-phalcon/nginx_site.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
  composer:
      container_name: composer
      restart: 'no'
      image: composer/composer:php7
      command: update
      working_dir: /code
      volumes:
        - ./apacs:/code   
  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs
  solr:
    build:
      context: ./infrastructure/solr/
      dockerfile: ./infrastructure/solr/Dockerfile
    container_name: solr
    ports:
      - "8989:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
        - ./infrastructure/solr/solr_conf:/opt/solr/server/solr/configsets/solr_conf
  indexer:
    container_name: indexer
    build:
        context: ./
        dockerfile: ./infrastructure/indexing/Dockerfile_dev
    volumes:
      - ./indexing:/usr/src/app/
    environment:
      - PYTHON_ENV=DEV
networks:
    default:
