version: '2'
services:
  phalcon:
    build:
      context: ./
      dockerfile: ./infrastructure/docker_webserver/Dockerfile_prod
    container_name: webserver
    ports:
      - "80:80"
    environment:
      - PROD_DEV=PROD
  solr:
    container_name: solr
    build:
      context: ./infrastructure/solr/
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install --no-dev
    working_dir: /apacs
    volumes:
      - ./apacs:/apacs      
