version: '3.3'
services:

  apacs-tests:
    build:
      context: ./
      dockerfile: ./infrastructure/php-fpm-phalcon/Dockerfile_prod
    image: apacs:latest
    container_name: apacs-tests
    depends_on:
      - mysql-tests
      - solr
    environment:
      - APACS_ACCESS_CTRL_NAME=FakeAccessController

      - APACS_DB_CHARSET=utf8
      - APACS_DB_DATABASE=apacs-tests-db
      - APACS_DB_HOST=mysql-tests
      - APACS_DB_PASSWORD=123456
      - APACS_DB_PORT=3306
      - APACS_DB_USER=dev

      - APACS_IMAGE_PATH=local
      - APACS_IMAGE_PROTOCOL=http

      - ENVIRONMENT=DEVELOPMENT
      
      - SOLR_SCHEME=http
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_PATH=/solr/apacs_core
      - SOLR_USERNAME=kbharkiv
      - SOLR_PASSWORD=6nXSaEJBH7
      
      - SOLR_TIMEOUT=10

  mysql-tests:
    image: mysql:5.7
    container_name: mysql-tests
    volumes:
      - ./apacs/tests/TestHelpers/db-test-data:/docker-entrypoint-initdb.d
      - ./infrastructure/db/config/my_dev.cnf:/etc/mysql/conf.d/my_dev.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs-tests-db

  nginx:
      image: nginx:alpine
      container_name: nginx
      depends_on:
        - apacs-tests
      volumes:
        - ./infrastructure/nginx/nginx_site.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

  solr:
    image: library/solr:6.6.3
    container_name: solr
    ports:
      - "8989:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
        - ./infrastructure/solr/solr_conf:/opt/solr/server/solr/configsets/solr_conf

networks:
    default:
