version: '2'
services:
  phalcon:
    build: ./docker_webserver/
    container_name: webserver
    privileged: true
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./apacs:/var/www/
    environment:
      - PROD_DEV=DEV
  db:
    image: mysql
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./apacs/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: apacs
  solr:
    image: library/solr
    container_name: solr
    ports:
      - "8988:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_core
      - /opt/solr/server/solr/configsets/solr_conf/apacs_core
    volumes:
        - ./solr_conf:/opt/solr/server/solr/configsets/solr_conf
  solr_stats:
    image: library/solr
    container_name: solr_stats
    ports:
      - "8989:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - apacs_stats
      - /opt/solr/server/solr/configsets/solr_conf/apacs_stats
    volumes:
        - ./solr_conf/:/opt/solr/server/solr/configsets/solr_conf/
  solr_stats_refresher:
    image: xordiv/docker-alpine-cron
    container_name: solr_stats_refresher
    links:
      - solr_stats
    environment:
      - CRON_STRINGS=* * * * * wget -qO- --no-cache --post-data="command=full-import&verbose=false&clean=false&commit=true&optimize=false&core=apacs_stats&name=dataimport" http://solr_stats:8983/solr/apacs_stats/dataimport?indent=on && echo '$$(date)  Got system_exceptions'
