FROM python:3

WORKDIR /usr/src/app

# Install cron
RUN apt-get update
RUN apt-get install -y cron

# Install requirements
COPY ./indexing/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Add source code
COPY ./indexing ./
COPY .env_dev /usr/src/app/env.cfg

RUN crontab /usr/src/app/crontab
RUN chmod +x /usr/src/app/cron.sh
ENTRYPOINT cron && tail -f /dev/null