FROM python:2

WORKDIR /usr/src/app


# Install requirements
COPY ./indexing/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

#Add source code
COPY ./indexing ./

COPY ./.env /etc

ENTRYPOINT [ "python", "/usr/src/app/cron.py" ]
