FROM php:7.1-fpm-alpine3.8

# install make tools, clone phalcon, build it and remove tmp folders and packages
RUN \
    apk add git autoconf file g++ gcc libc-dev make pkgconf re2c libtool \
    check check-dev cyrus-sasl-dev libsodium-dev libssh2-dev imagemagick-dev yaml-dev --no-cache && \
    cd ~ && git clone https://github.com/phalcon/cphalcon.git && \
    cd ~/cphalcon && git checkout v3.4.2 && \
    cd ~/cphalcon/build && ./install && \
    docker-php-ext-enable phalcon && \
    rm -rf ~/cphalcon && \
    apk del git autoconf make m4 perl g++ gcc \
    musl-dev libc-dev check-dev cyrus-sasl-dev libsodium-dev libssh2-dev yaml-dev openssl-dev imagemagick-dev zlib-dev

WORKDIR /code

#ENV MAX_EXECUTION_TIME=90

# Set Max execution time
#RUN sed -i "s@^max_execution_time = .*@max_execution_time = $MAX_EXECUTION_TIME@" /etc/php5/apache2/php.ini
#RUN sed -i "s@^output_buffering = .*@output_buffering = Off@" /etc/php5/apache2/php.ini

#RUN echo 'xdebug.remote_enable = 1 \n\
#xdebug.remote_host = 192.168.10.124 \n\
#xdebug.remote_port = 9000 \n\
#xdebug.remote_autostart=1 \n\
#xdebug.remote_handler = dbgp \n\
#xdebug.remote_mode = req \n\
#xdebug.profiler_enable=0 \n\
#xdebug.remote_log="/tmp/xdebug.log" \n\
#xdebug.profiler_enable_trigger=1 \n\
#xdebug.idekey="xdebug" \n\
#xdebug.profiler_output_dir = "/var/www/html"' >> /etc/php5/apache2/php.ini
