FROM 282251075226.dkr.ecr.eu-west-1.amazonaws.com/phalcon-base:latest

COPY ./infrastructure/php-fpm-phalcon/php-override.ini.prod /usr/local/etc/php/conf.d/php-ini-overrides.ini
COPY ./apacs /code
WORKDIR /code

RUN composer install
