SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `burial_addresses`;
DROP TABLE IF EXISTS `burial_birthplaces`;
DROP TABLE IF EXISTS `burial_burials`;
DROP TABLE IF EXISTS `burial_cemetaries`;
DROP TABLE IF EXISTS `burial_chapels`;
DROP TABLE IF EXISTS `burial_civilstatuses`;
DROP TABLE IF EXISTS `burial_deathcauses`;
DROP TABLE IF EXISTS `burial_deathplaces`;
DROP TABLE IF EXISTS `burial_floors`;
DROP TABLE IF EXISTS `burial_hoods`;
DROP TABLE IF EXISTS `burial_institutions`;
DROP TABLE IF EXISTS `burial_parishes`;
DROP TABLE IF EXISTS `burial_persons`;
DROP TABLE IF EXISTS `burial_persons_deathcauses`;
DROP TABLE IF EXISTS `burial_persons_positions`;
DROP TABLE IF EXISTS `burial_persons_sex`;
DROP TABLE IF EXISTS `burial_positions`;
DROP TABLE IF EXISTS `burial_relationtypes`;
DROP TABLE IF EXISTS `burial_streets`;
DROP TABLE IF EXISTS `burial_workplaces`;
SET FOREIGN_KEY_CHECKS = 1;