FROM szeist/phalcon-apache2

RUN apt-get update
RUN apt-get install phpunit --assume-yes

ENV MAX_EXECUTION_TIME=90

# Set Max execution time
RUN sed -i "s@^max_execution_time = .*@max_execution_time = $MAX_EXECUTION_TIME@" /etc/php5/apache2/php.ini
RUN sed -i "s@^output_buffering = .*@output_buffering = Off@" /etc/php5/apache2/php.ini

#RUN echo 'xdebug.remote_enable = 1 \n\
#xdebug.remote_host = 192.168.10.124 \n\
#xdebug.remote_port = 9000 \n\
#xdebug.remote_autostart=1 \n\
#xdebug.remote_handler = dbgp \n\
#xdebug.remote_mode = req \n\
#xdebug.profiler_enable=0 \n\
#xdebug.remote_log="/tmp/xdebug.log" \n\
#xdebug.profiler_enable_trigger=1 \n\
#xdebug.idekey="xdebug" \n\
#xdebug.profiler_output_dir = "/var/www/html"' >> /etc/php5/apache2/php.ini
