CREATE TABLE `burial_persons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstnames` char(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `lastname` char(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `birthname` char(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ageYears` int(11) DEFAULT NULL,
  `ageMonth` decimal(4,2) DEFAULT NULL,
  `dateOfBirth` date DEFAULT NULL,
  `dateOfDeath` date DEFAULT NULL,
  `deathplaces_id` int(11) DEFAULT NULL,
  `civilstatuses_id` int(11) DEFAULT NULL,
  `birthplaces_id` int(11) DEFAULT NULL,
  `birthplaceOther` char(125) COLLATE utf8_danish_ci DEFAULT NULL,
  `yearOfBirth` int(11) DEFAULT NULL,
  `adressOutsideCph` char(125) COLLATE utf8_danish_ci DEFAULT NULL,
  `sex_id` int(11) DEFAULT NULL,
  `comment` text COLLATE utf8_danish_ci,
  `ageWeeks` decimal(4,2) DEFAULT NULL,
  `ageDays` decimal(4,2) DEFAULT NULL,
  `ageHours` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_begrav_persons.deathplace_id_to_begrav.deathplace.id_idx` (`deathplaces_id`),
  KEY `FK_begrav_person.civilstatuses_to_begrav_civilstatuses.id_idx` (`civilstatuses_id`),
  KEY `FK_begrav_person.birthplace_id_to_begrav_birthplaces.id_idx` (`birthplaces_id`),
  CONSTRAINT `FK_burial_person.birthplaces_id_to_burial_birthplaces.id` FOREIGN KEY (`birthplaces_id`) REFERENCES `burial_birthplaces` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `FK_burial_person.civilstatuses_to_burial_civilstatuses.id` FOREIGN KEY (`civilstatuses_id`) REFERENCES `burial_civilstatuses` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `FK_burial_persons.deathplace_id_to_burial.deathplace.id` FOREIGN KEY (`deathplaces_id`) REFERENCES `burial_deathplaces` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;
